name: memoraisa
description: "Memoraisa"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.3
  package_info_plus: ^8.1.2
  shared_preferences: ^2.3.5
  dio: ^5.7.0
  file_picker: ^10.1.9
  slang: ^4.7.2
  slang_flutter: ^4.7.0
  flutter_dotenv: ^5.2.1
  archive: ^4.0.7
  xml: ^6.5.0
  hive: ^2.2.3
  syncfusion_flutter_pdf: ^29.2.9
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/img/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/img/icon.png
    - assets/img/
    - .env
